### PR TITLE
Updated auth scheme and use V5 vehicle list

### LINKED ISSUE #38: Server http statusCode 403 - only on status node
Since today I have been receiving statusCode 403 on the Get Node. Other nodes work fine.

To reproduce just drag a new get node into a flow - configure it correctly and trigger it over an inject node.

Error: 
Error: Server http statusCode 403

The car installed an update today: 11/2023.73 on an i4 eDrive40

### PR DESCRIPTION
**Pull request by jkellerer**
This PR fixes the auth problem that started to appear the last couple of days ago.

The auth flow is updated based on the logic from https://github.com/bimmerconnected/bimmer_connected

May fix #38 (definitely fixes getting vehicle list and status)

### CODE REVIEW

**Comment by arneman** [comment]
I patched the files manually and can confirm that this fix works. Thanks to @jkellerer

**Comment by locke987** [comment]
Looks good from my side as well after manually patching, thanks a lot!

**Comment by krauskopf** [comment]
Thanks to @jkellerer for the greate contribution. Credits go to him.

**Comment by bummzulu** [comment]
works for me, thanks everyone! i4 used in EMEA

**Pull request merged**
