### PR TITLE
Add captcha, oauth store and token refresh

### LINKED ISSUE #42: Stopped working today statusCode 401
[car-bmw-list:BMW] Error: Server send http statusCode 401 on stage 1
Bimmerconnected reports a similar issue.

### PR DESCRIPTION
**Pull request by jkellerer**
This fixes #42 by porting changes from [bimmer_connected](https://github.com/bimmerconnected/bimmer_connected) into this project.

There is a new input field to enter the captcha token that can be generated using the ROW or USA links in the hint:

image

If you receive error 429 (too many requests), you may need to wait for 24 hours and try again. Since previously the initial login was retried infinitelly, it probably affects most accounts. After this PR is applied a login will not be attempted when no bearer token is present (initial state) and the captcha is older than 5 minutes.

This PR also introduces a bearer token store in the global context to avoid the initial login which now always requires a new captcha token. Tokens are encrypted (AES256) using the CD password to avoid exposure in the global context. This feature depends on the persistent context storage being enabled. E.g. `localfilesystem`: 

```
9 Dec 18:59:30 - [info] Context store  : 'default' [module=localfilesystem]
```

### CODE REVIEW

**Comment by jkellerer** [comment]
Small update, got it working. Looks like the ROW captcha is different now. Will finish the PR.

**Comment by rsteininger** [comment]
hi there, 
I tried the new suggestion today, and initially, it looked good. However, we have two bmws and it seems, whichever one I do last, that is working. I have one login for both BUT was using 2 different tokes (two accounts created in the bmw node). That was my setup in the bimmerconnected CLI configuration and it worked well that way. 
However, if I do the same in node red, I now get this error message for whichever one is the "previously" changed. The "last" edited one works fine:
9/12/2024, 15:22:16[node: get bmw x1](http://192.168.10.199:1880/#)
msg : error
"ReferenceError: reallyExpired is not defined"

**Comment by jkellerer** [comment]
@rsteininger , thanks a lot for the feedback. `ReferenceError: reallyExpired`, can see where it comes from. I'm also using it with 2 BMW but with 2 CD accounts and it works so far. A single account likely suffers from independent login attempts. Will refactor it a bit to make sure the shared state is checked first (e.g. if you use the same account for 2 different cars).

**Comment by jkellerer** [comment]
@rsteininger, maybe you want to try the latest updates. It should work better now with multiple requests.

**Comment by rsteininger** [comment]
> @rsteininger, maybe you want to try the latest updates. It should work better now with multiple requests.

Sorry for the slow reply. Only managed to implement and test the latest version now. 
I can confirm that both work
- 1 bmw account with two tokens, one for each car we have and also
- tried remote commends (flash lights) which worked fine
Many thanks for all the hard work!

**Comment by Vialet** [comment]
Could you make this PR Public so it can be updated via NR?

**Comment by jkellerer** [comment]
@krauskopf would you mind reviewing the pr? It looks like it works now (even when cd servers are offline for half a day which recently happened on Tuesday).

**Comment by krauskopf** [comment]
Thanks @jkellerer for the greate contribution. Looks good to me!

**Pull request merged**
