### PR TITLE
Update user-agent to fix 403

### PR DESCRIPTION
**Pull request by dzett**
Hi @krauskopf, 
as suggested in https://github.com/krauskopf/node-red-contrib-car-bmw/issues/15#issuecomment-1140243316 I have updated the user agent string. I don't know your workflow, but "works on my machine" ;-)
Best,
dzett

### CODE REVIEW

**Comment by dzett** [comment]
Fix is maybe a bit too quick-and-dirty, I guess the "row" part of the user agent should actually depend on the region setting. 
Also noticed that all fields in the status of the BMW List node are now in miles...

**Comment by jkellerer** [comment]
Have omitted the “;row” suffix and mileage and range remain in km. The suffix isn’t required to fix the auth issue.

**Comment by krauskopf** [comment]
Thanks @dzett , works also on my machine ;-). Will remove the suffix and make a release.

**Comment by krauskopf** [comment]
Thanks @jkellerer , will remove the row and make a releas.

**Pull request merged**
